apiVersion: v1
kind: Service
metadata:
  labels:
    service: dongfeng-websocket
  namespace: dongfeng-back
  name: dongfeng-websocket
spec:
  type: ClusterIP
  ports:
  - name: api-port
    port: 8890
    targetPort: "api-port"
    protocol: TCP
  selector:    
      app: dongfeng-websocket